version: "3.9"
services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "3443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build: .
    ports:
      - "3000:3000"